In [1]:
import pandas as pd

df = pd.read_csv('./output_table_Gujarat_State_Year_Book_2021-22_page_1.csv')
df.columns

Index(['S.N.', 'District', 'Site Name', 'Latitude', 'Longitude', 'pH', 'EC',
       'TDS', 'TH', 'CO3', 'HCO3', 'Cl', 'S04', 'NO3', 'F', 'Alkalinity', 'Ca',
       'Mg', 'Na', 'K', 'SiO2', 'SAR'],
      dtype='object')

In [2]:
import pandas as pd
import glob

df_ls = []
for file in glob.glob('*.csv'):
    df = pd.read_csv(file)
    df.columns = ['S.N.', 'District', 'Site Name', 'Latitude', 'Longitude', 'pH', 'EC',
       'TDS', 'TH', 'CO3', 'HCO3', 'Cl', 'S04', 'NO3', 'F', 'Alkalinity', 'Ca',
       'Mg', 'Na', 'K', 'SiO2', 'SAR']
    df_ls.append(df)

df = pd.concat(df_ls).reset_index(drop=True)
df

,S.N.,District,Site Name,Latitude,Longitude,pH,EC,TDS,TH,CO3,...,S04,NO3,F,Alkalinity,Ca,Mg,Na,K,SiO2,SAR
0,513.0,Surendranagar,Kankavati,23.06389,71.36444,7.83,1932,1294,390.0,0.0,...,90.0,65.00,0.69,220.0,88.0,41.0,262.0,2.6,32.0,5.77
1,514.0,Surendranagar,Khambhada,22.89278,71.52361,8.20,2321,1555,410.0,0.0,...,135.0,23.00,0.52,460.0,124.0,24.0,294.0,107.0,27.0,6.31
2,515.0,Surendranagar,Rajsitapur,22.83778,71.59667,7.64,2678,1794,801.0,0.0,...,39.0,1.50,0.48,140.0,208.0,68.0,272.0,5.1,31.0,4.18
3,516.0,Surendranagar,Latuda,22.79841,71.61542,7.96,1540,1032,370.0,0.0,...,66.0,0.95,3.00,240.0,76.0,44.0,174.0,6.7,30.0,3.93
4,517.0,Surendranagar,Surendranagar 2,22.71722,71.61667,8.19,3166,2121,350.0,0.0,...,190.0,33.00,2.70,540.0,48.0,56.0,618.0,2.6,56.0,14.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
533,267.0,Kutchch,Desalpur,23.75020,70.68102,7.42,768,515,180.0,0.0,...,70.0,3.20,0.15,150.0,40.0,19.0,95.0,10.0,21.0,3.08
534,268.0,Kutchch,Ratanpar Khadir,23.86210,70.3623,7.73,4419,2961,701.0,0.0,...,310.0,13.00,0.78,330.0,96.0,112.0,712.0,17.0,21.0,11.70
535,269.0,Kutchch,Rapar,23.56689,70.65177,7.60,2942,1971,400.0,0.0,...,538.0,33.00,0.93,230.0,132.0,17.0,552.0,26.0,29.0,12.00
536,270.0,Kutchch,Kuda,23.53444,70.44038,7.35,1464,981,410.0,0.0,...,25.0,0.31,1.04,500.0,104.0,36.0,125.0,18.0,44.0,2.68
537,271.0,Kutchch,Kharoi,23.46007,70.35659,7.62,1304,874,400.0,0.0,...,77.0,1.50,0.33,230.0,68.0,56.0,105.0,4.2,21.0,2.28

In [4]:
df.to_csv('../../refined-data/tabula-Gujarat_State_Year_Book_2021-22.csv', index=False)